### PR TITLE
Fix DE numerical ordinal matching

### PR DESCRIPTION
**Pull request by sebastianmika**
The numerical ordinal matching rule in DE is too broad. An ordinal like "1." may not be proceeded or followed by numbers.

* Added negative lookbehind - avoids matching the first "1." in "1.1" as an ordinal.
* Added negative lookahead - avoids matching the second "1." in "1.1. as an ordinal

### CODE REVIEW

**Comment by niteria** [comment]
I suspect this might affect the generated classifiers.
Can you run:
```
stack build :duckling-regen-exe && stack exec duckling-regen-exe
```
and amend the generated files to the pull request?

**Comment by sebastianmika** [comment]
Sorry, thought that this would be generated on the fly

**Comment by niteria** [comment]
No worries, I'd be nice for it to be somehow handled by the build system, but we haven't found a nice way to do that yet.

**Comment by niteria** [comment]
Merging, thank you!

**Pull request closed without merging**
