### PR TITLE
Remove mkLatent on FR time's rules for 'matin' and 'soir'

### PR DESCRIPTION
**Pull request by amenella**
Remove `mkLatent` rule in order to parse *matin* and *soir* without any determiner.

### CODE REVIEW

**Comment by patapizza** [comment]
Hi @amenella,

I'm not totally sold on this. Can you share a few examples in why this is needed?

Thanks.

**Comment by amenella** [comment]
Without removing `mkLatent`, the following case (actually in french) would parse nothing at all:
  * *user:* j'aimerais prendre un rendez-vous pour demain (i would like to take an appointment for tomorrow)
  * *bot:* Bien sur ! Avez-vous une préférence pour le matin, l'après-midi ou le soir ? (Sure ! do you prefer in the morning, the afternoon or the evening ?)
  * *user:* matin (morning)

I know it's not a very strong usecase, as if our user said `le matin` it would have been parsed, but i think we agree to cover all possible usecases.

What do you think @patapizza ?

**Comment by patapizza** [comment]
@amenella Thanks for providing more context.

We can't return latent times such as `matin` as is, as this really depends on the business logic.
One thing we could do is to return latent times with a special flag on request (might fit under the assumptions idea #29).

Any chance quick replies, levenshtein distance or even a simple regex would work for this specific use case in the meantime?

**Comment by patapizza** [comment]
Closing in favor of #73.

**Comment by amenella** [comment]
We handle the case by processing it manually for now, it's not a big deal but it would have been cleaner to let duckling handle it for us. Thanks anyway @patapizza !

**Pull request closed without merging**
