### PR TITLE
Add Cantonese support to date time into ZH

### PR DESCRIPTION
**Pull request by kkpoon**
Add the [Cantonese](https://en.wikipedia.org/wiki/Cantonese) (the official spoken language used in Hong Kong) support to date time

- updated Duration ZH corpus
- updated Time ZH rules and corpus
- updated TimeGrain ZH rules

### CODE REVIEW

**Comment by niteria** [comment]
Hi,
Could you run `stack build :duckling-regen-exe && stack exec duckling-regen-exe` and amend the results to your pull request?
I expect your change to affect the generated classifiers.

Thanks!

**Comment by kkpoon** [comment]
Hi @niteria,

The classifier of ZH is regenerated.

I pushed as fixup

Should I squash the commits into one?

Thanks

**Comment by niteria** [comment]
Feel free to keep the commits unsquashed, we will squash when we merge.

Looks like the tests aren't passing, I suspect you will need to extend Rules as well.
We explain what Corpus and Rules are for here: https://github.com/facebookincubator/duckling#extending-duckling.
Note that changes to Rules are also likely to affect generated classifiers.

If you want to test your changes locally we have instructions for that here: https://github.com/facebookincubator/duckling#extending-duckling

Thanks!

**Comment by kkpoon** [comment]
Got it.

I rename the PR to WIP, I need some time to work on it.

And, in the regex, the string characters are converted to `\xAABB` , any convenience tool in command line, or plugin in atom.io could help to convert it back and forth?

Thanks

**Comment by niteria** [comment]
You can do that from GHCi (which you can get with `stack repl --no-load`):
```
Prelude> import Text.Printf (printf)
Prelude Text.Printf> putStrLn $ printf "\\x%04x" (fromEnum 'ą')
\x0105
```

If you want to do that for the entire string, this stackoverflow answer looks useful: https://stackoverflow.com/a/39236910/87721

**Comment by kkpoon** [comment]
The rules are updated. Thanks

**Comment by niteria** [comment]
Merged, thank you!

**Pull request closed without merging**
